// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvGksMPlKHIwC4NpGWNb2JtZUyfp6i3bs',
    appId: '1:27405714905:web:ec71aa68f2030d86a685c8',
    messagingSenderId: '27405714905',
    projectId: 'fasum-app-25e06',
    authDomain: 'fasum-app-25e06.firebaseapp.com',
    storageBucket: 'fasum-app-25e06.firebasestorage.app',
    measurementId: 'G-685085XPZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7zQu27LoXhOhckkzyl5BSapuV43Vh780',
    appId: '1:27405714905:android:ca6dcf396870868fa685c8',
    messagingSenderId: '27405714905',
    projectId: 'fasum-app-25e06',
    storageBucket: 'fasum-app-25e06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-9wl0NarYAHa4mqKvVrqBabCgOgQy1R0',
    appId: '1:27405714905:ios:6830e50fc1bf52bfa685c8',
    messagingSenderId: '27405714905',
    projectId: 'fasum-app-25e06',
    storageBucket: 'fasum-app-25e06.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-9wl0NarYAHa4mqKvVrqBabCgOgQy1R0',
    appId: '1:27405714905:ios:6830e50fc1bf52bfa685c8',
    messagingSenderId: '27405714905',
    projectId: 'fasum-app-25e06',
    storageBucket: 'fasum-app-25e06.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvGksMPlKHIwC4NpGWNb2JtZUyfp6i3bs',
    appId: '1:27405714905:web:8d3421b26f2b3cc2a685c8',
    messagingSenderId: '27405714905',
    projectId: 'fasum-app-25e06',
    authDomain: 'fasum-app-25e06.firebaseapp.com',
    storageBucket: 'fasum-app-25e06.firebasestorage.app',
    measurementId: 'G-E4FS7WHS02',
  );

}