// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa6v-urdbPjvPEhEx6k8AM2q-SHJMgsLY',
    appId: '1:263828219032:web:f54416c2d8c249b2975ced',
    messagingSenderId: '263828219032',
    projectId: 'fasum-app-3bde0',
    authDomain: 'fasum-app-3bde0.firebaseapp.com',
    storageBucket: 'fasum-app-3bde0.firebasestorage.app',
    measurementId: 'G-VDKWNS1RZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbpY797_X4p6VfRwdU8ez9HV9cEEKK1AI',
    appId: '1:263828219032:android:d59116c70170649e975ced',
    messagingSenderId: '263828219032',
    projectId: 'fasum-app-3bde0',
    storageBucket: 'fasum-app-3bde0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGmX0FDgMr4kS7xJOSPQCRLujZNo68aZA',
    appId: '1:263828219032:ios:e21a0696b6e7b575975ced',
    messagingSenderId: '263828219032',
    projectId: 'fasum-app-3bde0',
    storageBucket: 'fasum-app-3bde0.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGmX0FDgMr4kS7xJOSPQCRLujZNo68aZA',
    appId: '1:263828219032:ios:e21a0696b6e7b575975ced',
    messagingSenderId: '263828219032',
    projectId: 'fasum-app-3bde0',
    storageBucket: 'fasum-app-3bde0.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa6v-urdbPjvPEhEx6k8AM2q-SHJMgsLY',
    appId: '1:263828219032:web:bef7de8ccacfb1be975ced',
    messagingSenderId: '263828219032',
    projectId: 'fasum-app-3bde0',
    authDomain: 'fasum-app-3bde0.firebaseapp.com',
    storageBucket: 'fasum-app-3bde0.firebasestorage.app',
    measurementId: 'G-83ZJGSVR69',
  );

}