name: fasum
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.1
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0
  geolocator: ^14.0.0
  cloud_firestore: ^5.6.6
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  url_launcher: ^6.3.1
  http: ^1.4.0 
  shimmer: ^3.0.0
  firebase_messaging: ^15.2.6
  flutter_local_notifications: ^19.2.1
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.0.15
  provider: ^6.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/fasum_icon_512.png"
  min_sdk_android: 23
  
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fasum_icon.png
    - assets/fasum_icon_512.png
